# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38a5eaffdc37b0a17bdd8e65efccff258535b6240deefc0b350b2046ada58e68e35da5362d9444329f07330e09c33fdd9e52ea1c4b4e471b281029e4a8069dd2

test:
  secret_key_base: aadcca5fab4fed1e701da2960ec449a2aceaa46d6ea583fe924334d6fb46b4dd582c1ec9cc5f2ede213309463dd5f9d3c558909bd04982020386ea66e59ff7a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
